
spring:
application:
  name: CONFIG-DEV
eureka:
  client:
    register-with-eureka: false # Indicates whether this instance registers itself with the Eureka server
    fetch-registry: false # Indicates whether this instance should fetch the registry information from the Eureka server
    service-url:
      defaultZone: http://localhost:8761/eureka/
